[project]
name = "havenly"
version = "0.1.0"
description = "An End to End Real Estate Management System"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "ruff>=0.12.10",
]
